# Generated by Django 4.1.4 on 2024-02-22 12:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='decorations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dec_desc', models.TextField(null=True)),
                ('dec_title', models.CharField(max_length=250, null=True)),
                ('dec_image', models.FileField(null=True, upload_to='')),
                ('personone', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dec_id', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
