# Generated by Django 4.1.4 on 2024-02-22 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('decorations', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='decorations',
            old_name='personone',
            new_name='dec_id',
        ),
    ]
