# Generated by Django 5.0.4 on 2024-05-15 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decorations', '0002_rename_personone_decorations_dec_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='decorations',
            name='amount',
            field=models.IntegerField(null=True),
        ),
    ]
