# Generated by Django 5.0.4 on 2024-06-11 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decorations', '0003_decorations_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('files', models.FileField(null=True, upload_to='')),
            ],
        ),
        migrations.RemoveField(
            model_name='decorations',
            name='dec_image',
        ),
        migrations.AddField(
            model_name='decorations',
            name='dec_image',
            field=models.ManyToManyField(to='decorations.file'),
        ),
    ]
