# Generated by Django 4.1.4 on 2024-02-19 04:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organizer_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='events',
            name='artist_id',
        ),
        migrations.RemoveField(
            model_name='events',
            name='dec_id',
        ),
        migrations.AddField(
            model_name='events',
            name='buserid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eventartistuserid', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='events',
            name='eventdescription',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='events',
            name='eventname',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='events',
            name='uid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='userbookingid', to=settings.AUTH_USER_MODEL),
        ),
    ]
