# Generated by Django 4.1.4 on 2024-02-16 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_bookings_delete_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookings',
            name='status',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
