# Generated by Django 5.0.4 on 2024-05-23 03:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_bookings_status'),
        ('decorations', '0003_decorations_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookings',
            name='buserid',
        ),
        migrations.AddField(
            model_name='bookings',
            name='decid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookuserid', to='decorations.decorations'),
        ),
    ]
