# Generated by Django 5.0.4 on 2024-05-23 03:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_remove_bookings_buserid_bookings_decid'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='programs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('art_desc', models.TextField(null=True)),
                ('art_title', models.CharField(max_length=250, null=True)),
                ('art_image', models.FileField(null=True, upload_to='')),
                ('amount', models.IntegerField(null=True)),
                ('art_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='art_id', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
