# Generated by Django 5.0.4 on 2024-05-23 05:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_programs'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookings',
            name='pgid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookuserid', to='bookings.programs'),
        ),
    ]
