# Generated by Django 5.0.6 on 2024-05-24 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0006_bookings_pgid'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookings',
            name='district',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='bookings',
            name='location',
            field=models.CharField(default='', max_length=250),
        ),
    ]
