# Generated by Django 5.0.4 on 2024-06-11 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0007_bookings_district_bookings_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookings',
            name='district',
            field=models.CharField(choices=[('', 'SELECT'), ('Thrissur', 'Thrissur'), ('Pathanamthitta', 'Pathanamthitta'), ('Alappuzha', 'Alappuzha'), ('Kollam', 'Kollam'), ('Idukki', 'Idukki'), ('Thiruvananthapuram', 'Thiruvananthapuram'), ('Palakkad', 'Palakkad'), ('Kottayam', 'Kottayam'), ('Kozhikkode', 'Kozhikkode'), ('Kannur', 'Kannur'), ('Malappuram', 'Malappuram'), ('Ernamkulam', 'Ernamkulam'), ('Wayanad', 'Wayanad'), ('Kasaragod', 'Kasaragod')], default='', max_length=250),
        ),
    ]
