# Generated by Django 5.0.4 on 2024-06-14 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0008_alter_bookings_district'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookings',
            name='district',
            field=models.CharField(choices=[('Kollam', 'Kollam'), ('Thrissur', 'Thrissur'), ('', 'SELECT'), ('Thiruvananthapuram', 'Thiruvananthapuram'), ('Idukki', 'Idukki'), ('Wayanad', 'Wayanad'), ('Palakkad', 'Palakkad'), ('Pathanamthitta', 'Pathanamthitta'), ('Ernamkulam', 'Ernamkulam'), ('Alappuzha', 'Alappuzha'), ('Malappuram', 'Malappuram'), ('Kozhikkode', 'Kozhikkode'), ('Kasaragod', 'Kasaragod'), ('Kottayam', 'Kottayam'), ('Kannur', 'Kannur')], default='', max_length=250),
        ),
    ]
