# Generated by Django 5.0.2 on 2024-02-17 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inbox', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='events',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='events',
            name='date',
        ),
        migrations.RemoveField(
            model_name='events',
            name='etime',
        ),
        migrations.RemoveField(
            model_name='events',
            name='stime',
        ),
        migrations.AddField(
            model_name='events',
            name='message',
            field=models.TextField(null=True),
        ),
    ]
