# Generated by Django 5.0.2 on 2024-02-18 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inbox', '0003_rename_events_inbox'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inbox',
            old_name='service_person',
            new_name='personone',
        ),
        migrations.RenameField(
            model_name='inbox',
            old_name='org_id',
            new_name='persontwo',
        ),
    ]
