# Generated by Django 4.1.4 on 2024-02-19 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inbox', '0004_rename_service_person_inbox_personone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inbox',
            name='datetime',
            field=models.DateTimeField(null=True),
        ),
    ]
