# Generated by Django 4.1.4 on 2024-02-10 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='status',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
