# Generated by Django 5.0.2 on 2024-02-12 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0002_register_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='experience',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='register',
            name='address',
            field=models.TextField(null=True),
        ),
    ]
