# Generated by Django 4.1.4 on 2024-02-16 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0003_register_experience_alter_register_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='amount',
            field=models.IntegerField(null=True),
        ),
    ]
