# Generated by Django 4.1.4 on 2024-02-16 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0004_register_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='profile',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
