# Generated by Django 5.0.2 on 2024-02-17 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0005_register_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='amountperhour',
            field=models.IntegerField(null=True),
        ),
    ]
