# Generated by Django 5.0.2 on 2024-02-20 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0006_register_amountperhour'),
    ]

    operations = [
        migrations.RenameField(
            model_name='register',
            old_name='name',
            new_name='dob',
        ),
        migrations.AddField(
            model_name='register',
            name='gender',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='register',
            name='specialskills',
            field=models.TextField(default='', max_length=500),
        ),
    ]
