# Generated by Django 5.0.2 on 2024-02-20 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0007_rename_name_register_dob_register_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='gender',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
