# Generated by Django 5.0.2 on 2024-02-20 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0008_alter_register_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='companyname',
            field=models.CharField(default='', max_length=500),
        ),
    ]
