# Generated by Django 5.0.2 on 2024-02-25 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0010_rename_companyname_register_comp_org_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='previousworks',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
