# Generated by Django 5.0.2 on 2024-04-01 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0011_register_previousworks'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='city',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='register',
            name='idproof',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='register',
            name='pin',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='register',
            name='street',
            field=models.CharField(default='', max_length=50),
        ),
    ]
