# Generated by Django 5.0.2 on 2024-04-03 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0012_register_city_register_idproof_register_pin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='interest',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='register',
            name='pr_type',
            field=models.CharField(default='', max_length=50),
        ),
    ]
