# Generated by Django 4.1.4 on 2024-02-20 06:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaint', models.TextField(null=True)),
                ('datetime', models.DateTimeField(null=True)),
                ('status', models.IntegerField(default=0, null=True)),
                ('dec_art_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dec_art_id', to=settings.AUTH_USER_MODEL)),
                ('userid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cuid', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
