# Generated by Django 4.1.4 on 2024-02-20 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaint', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='title',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
