# Generated by Django 5.0.4 on 2024-05-15 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaint', '0002_complaint_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='response',
            field=models.TextField(null=True),
        ),
    ]
