# Generated by Django 4.1.4 on 2024-02-15 10:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedbackmsg', models.TextField(null=True)),
                ('ratings', models.IntegerField(null=True)),
                ('fuserid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fid', to=settings.AUTH_USER_MODEL)),
                ('uid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='uid', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
